# Generated by Django 5.2.4 on 2025-07-19 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrito',
            options={'permissions': [('puede_ver_carritos', 'Puede ver todos los carritos'), ('puede_limpiar_carritos', 'Puede limpiar carritos ajenos')], 'verbose_name': 'Carrito de compras', 'verbose_name_plural': 'Carritos de compras'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'ordering': ['-agregado'], 'permissions': [('puede_ver_items', 'Puede ver todos los ítems'), ('puede_modificar_items', 'Puede modificar ítems ajenos')], 'verbose_name': 'Ítem del carrito', 'verbose_name_plural': 'Ítems del carrito'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado'], 'permissions': [('puede_editar_producto', 'Puede editar productos'), ('puede_eliminar_producto', 'Puede eliminar productos'), ('puede_crear_producto', 'Puede crear productos'), ('puede_gestionar_inventario', 'Puede gestionar inventario'), ('puede_ver_reportes', 'Puede ver reportes de productos')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
    ]
