# Generated by Django 5.2.4 on 2025-07-19 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_carrito_options_alter_itemcarrito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado'], 'permissions': [('puede_ver_productos', 'Puede ver listado de productos'), ('puede_editar_producto', 'Puede editar cualquier producto'), ('puede_eliminar_producto', 'Puede eliminar productos'), ('puede_crear_producto', 'Puede crear nuevos productos'), ('puede_gestionar_inventario', 'Puede actualizar inventarios'), ('puede_ver_reportes', 'Puede acceder a reportes')], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
